# Generated by Django 5.2.4 on 2025-08-05 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='The unique ANDROID_ID of the device.', max_length=255, unique=True)),
                ('friendly_name', models.CharField(blank=True, help_text='e.g., Living Room TV, Office Display', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked')], default='active', max_length=20)),
                ('lock_message', models.TextField(blank=True, default='')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
