# Generated by Django 5.2.4 on 2025-11-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_code",
                    models.IntegerField(
                        help_text="Must match the 'versionCode' in build.gradle",
                        unique=True,
                    ),
                ),
                (
                    "version_name",
                    models.CharField(help_text="e.g. 1.0.2", max_length=50),
                ),
                (
                    "download_url",
                    models.URLField(
                        help_text="Direct link to the APK file (e.g., GitHub Release asset)"
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(
                        blank=True, help_text="What's new in this version?"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, help_text="If true, user cannot skip this update"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version_code"],
            },
        ),
    ]
